services:
  kolsor:
    image: node:22-alpine
    container_name: ${STACK_NAME}
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development # Cambiar a production para evitar logs
      - JWT_SECRET="${JWT_SECRET}"
      - DB_CONNECTION=mongodb://kolsor:${MONGO_PASSWORD}@mongo/kolsor?authSource=admin
    working_dir: /app
    volumes:
      - .:/app
    command: node dist/main.js
    
    ports:
      - 3033:3000

  mongo:
    image: mongo:latest
    container_name: ${STACK_NAME}_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kolsor
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data:
